### ISSUE TITLE
使用注解的方式配置权限虽然是官方推荐，但是实际用来不方便管理吧

### ISSUE THREAD

**Issue by zhuoyuehc** [wuyouzhuguli/SpringAll#12]
使用注解的方式配置权限虽然是官方推荐，但是实际用来不方便管理吧，难道要打开一个个文件才知道什么角色具可以访问那些，希望能补充传统的鉴权用法

**Comment by wuyouzhuguli** [comment]
可以参考我开源的权限系统【角色管理】模块
