### ISSUE TITLE
参照你的例子，使用springboot 2.1.7版本

### ISSUE THREAD

**Issue by yanglin1501804006** [wuyouzhuguli/SpringAll#17]
你好，我能参考你的文档教程，编写 springboot 2.1.7版本+ mysql 5.7.27 的 案例吗， 如果写的话，我引用你博客低版本教学链接【标注从你那里来】，这样OK吗？thanks

**Comment by wuyouzhuguli** [comment]
可以，不介意的话可以分享下你的博客链接，互相学习。




------------------ 原始邮件 ------------------
发件人: "yanglin1501804006"<notifications@github.com>;
发送时间: 2019年8月15日(星期四) 晚上11:49
收件人: "wuyouzhuguli/SpringAll"<SpringAll@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [wuyouzhuguli/SpringAll] 参照你的例子，使用springboot 2.1.7版本 (#17)




你好，我能参考你的文档教程，编写 springboot 2.1.7版本+ mysql 5.7.27 的 案例吗， 如果写的话，我引用你博客低版本教学链接【标注从你那里来】，这样OK吗？thanks

**Comment by yanglin1501804006** [comment]
我没有自己的博客，我是想着把你那个demo 用springboot 2.1.7 —— mysql 5.7.27实现一下，在文章里面标注一下你的原始链接哈。我倒时候写的时候，先让你那边看一下啦





在 2019-08-16 11:07:12，"mrbird" <notifications@github.com> 写道：
可以，不介意的话可以分享下你的博客链接，互相学习。




------------------ 原始邮件 ------------------
发件人: "yanglin1501804006"<notifications@github.com>;
发送时间: 2019年8月15日(星期四) 晚上11:49
收件人: "wuyouzhuguli/SpringAll"<SpringAll@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [wuyouzhuguli/SpringAll] 参照你的例子，使用springboot 2.1.7版本 (#17)




你好，我能参考你的文档教程，编写 springboot 2.1.7版本+ mysql 5.7.27 的 案例吗， 如果写的话，我引用你博客低版本教学链接【标注从你那里来】，这样OK吗？thanks
