### ISSUE TITLE
老哥, 博客是不是挂了

### ISSUE THREAD

**Issue by SethWen** [wuyouzhuguli/SpringAll#25]
博客比较成体系, 感谢了.

**Comment by tcxiaotudou** [comment]
没挂，只是需要开代理才比较顺畅。

**Comment by wuyouzhuguli** [comment]
静态博客，托管coding，速度还不错但是时常会无法访问；

现在托管到github了，速度一般，但是稳定。

**Comment by Mr-sang** [comment]
好的


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"fciasth"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月13日(星期五) 下午3:34
收件人:&nbsp;"wuyouzhuguli/SpringAll"<SpringAll@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [wuyouzhuguli/SpringAll] 老哥, 博客是不是挂了 (#25)




没挂，只是需要开代理才比较顺畅。
