### ISSUE TITLE
mrbird.cc访问太慢

### ISSUE THREAD

**Issue by hson08** [wuyouzhuguli/SpringAll#28]
大佬，你的博客访问速度比github还慢，偶尔运气好的时候打开就快一点，多数的时候菊花转半天没反应。这个问题能不能改善一下呢，一定请你喝肥皂水！

**Comment by wuyouzhuguli** [comment]
之前用github pages，感觉很慢，然后换成coding pages了，我这感觉访问速度提升了 😂，你那很慢的话可以科学上网试试。

**Comment by zlf2002171** [comment]
unsubscribe
2020-05-18 

zlf2002171 



发件人：mrbird <notifications@github.com>
发送时间：2020-03-18 11:26
主题：Re: [wuyouzhuguli/SpringAll] mrbird.cc访问太慢 (#28)
收件人："wuyouzhuguli/SpringAll"<SpringAll@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

Closed #28.
