### ISSUE TITLE
大佬，你的博客访问的时候好慢

### ISSUE THREAD

**Issue by Bryanlby** [wuyouzhuguli/SpringAll#5]
大佬，你的博客访问的时候好慢

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub For GitHub</a></sub>

**Comment by wuyouzhuguli** [comment]
码云，coding都部署过，感觉速度都慢😪

备用地址：[https://mrbirdd.gitee.io/blog/](https://mrbirdd.gitee.io/blog/)

**Comment by jkihi** [comment]
你好，这不是我的博客




祝：
   好！
   
'林佳杰'
在2019年03月26日 08:54，mrbird 写道：

码云，coding都部署过，感觉速度都慢😪

备用地址：https://mrbirdd.gitee.io/blog/

**Comment by wuyouzhuguli** [comment]
???

**Comment by jkihi** [comment]
您好，我还没有个人博客哈。有个公众号：itjie


在2019年03月26日 09:07，mrbird 写道：

???

**Comment by Bryanlby** [comment]
大佬，你的文章写得真的好，很详细，对于我来说受益匪浅

**Comment by jkihi** [comment]
可是我真的没有博客，您可能是看错了吧。


在2019年03月26日 13:35，Bryanlby 写道：

大佬，你的文章写得真的好，很详细，对于我来说受益匪浅

**Comment by wuyouzhuguli** [comment]
@jkihi  老哥，你自作多情一天了……


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)
